# Generated by Django 4.2.7 on 2023-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("desc", models.TextField()),
                ("year", models.IntegerField()),
                ("img", models.ImageField(blank=True, upload_to="gallery")),
            ],
        ),
    ]
